// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCySXCVurHqwa0vJp2va4pk_BbTuavRKRY',
    appId: '1:230544696248:web:09dadb2a7c6df24b40654d',
    messagingSenderId: '230544696248',
    projectId: 'bookia-edb87',
    authDomain: 'bookia-edb87.firebaseapp.com',
    storageBucket: 'bookia-edb87.firebasestorage.app',
    measurementId: 'G-2HWL18JHT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy59WmcSPVTHXueNf6Vtu1TrQVPmprEnk',
    appId: '1:230544696248:android:1055186bb79336d640654d',
    messagingSenderId: '230544696248',
    projectId: 'bookia-edb87',
    storageBucket: 'bookia-edb87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtPNfktdncvawFqIY625CHknoEYTS_orQ',
    appId: '1:230544696248:ios:138f4eb72ba9cdaa40654d',
    messagingSenderId: '230544696248',
    projectId: 'bookia-edb87',
    storageBucket: 'bookia-edb87.firebasestorage.app',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtPNfktdncvawFqIY625CHknoEYTS_orQ',
    appId: '1:230544696248:ios:138f4eb72ba9cdaa40654d',
    messagingSenderId: '230544696248',
    projectId: 'bookia-edb87',
    storageBucket: 'bookia-edb87.firebasestorage.app',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCySXCVurHqwa0vJp2va4pk_BbTuavRKRY',
    appId: '1:230544696248:web:e8c4a4f229f88e0140654d',
    messagingSenderId: '230544696248',
    projectId: 'bookia-edb87',
    authDomain: 'bookia-edb87.firebaseapp.com',
    storageBucket: 'bookia-edb87.firebasestorage.app',
    measurementId: 'G-CZB1G05R1C',
  );
}
